
reference: "/global/scratch/users/milesroberts/moi_lab_projects/grenenet-phase2/resources/Athaliana_447_TAIR10.fa"

# SAMPLES ====================================================================
root: "/global/scratch/projects/fc_moilab/projects/grenenet_phase2_poolseq/"

samples:
 - "MEAJM002-100_S100_L004"
 - "MEAJM002-101_S101_L004"
 - "MEAJM002-102_S102_L004"
 - "MEAJM002-103_S103_L004"
 - "MEAJM002-104_S104_L004"
 - "MEAJM002-105_S105_L004"
 - "MEAJM002-106_S106_L004"
 - "MEAJM002-107_S107_L004"
 - "MEAJM002-108_S108_L004"
 - "MEAJM002-109_S109_L004"
 - "MEAJM002-10_S10_L004"
 - "MEAJM002-110_S110_L004"
 - "MEAJM002-111_S111_L004"
 - "MEAJM002-112_S112_L004"
 - "MEAJM002-113_S113_L004"
 - "MEAJM002-114_S114_L004"
 - "MEAJM002-115_S115_L004"
 - "MEAJM002-116_S116_L004"
 - "MEAJM002-117_S117_L004"
 - "MEAJM002-118_S118_L004"
 - "MEAJM002-119_S119_L004"
 - "MEAJM002-11_S11_L004"
 - "MEAJM002-120_S120_L004"
 - "MEAJM002-121_S121_L004"
 - "MEAJM002-122_S122_L004"
 - "MEAJM002-123_S123_L004"
 - "MEAJM002-124_S124_L004"
 - "MEAJM002-125_S125_L004"
 - "MEAJM002-126_S126_L004"
 - "MEAJM002-127_S127_L004"
 - "MEAJM002-128_S128_L004"
 - "MEAJM002-129_S129_L004"
 - "MEAJM002-12_S12_L004"
 - "MEAJM002-130_S130_L004"
 - "MEAJM002-131_S131_L004"
 - "MEAJM002-132_S132_L004"
 - "MEAJM002-133_S133_L004"
 - "MEAJM002-134_S134_L004"
 - "MEAJM002-135_S135_L004"
 - "MEAJM002-136_S136_L004"
 - "MEAJM002-137_S137_L004"
 - "MEAJM002-138_S138_L004"
 - "MEAJM002-139_S139_L004"
 - "MEAJM002-13_S13_L004"
 - "MEAJM002-140_S140_L004"
 - "MEAJM002-141_S141_L004"
 - "MEAJM002-142_S142_L004"
 - "MEAJM002-143_S143_L004"
 - "MEAJM002-144_S144_L004"
 - "MEAJM002-145_S145_L004"
 - "MEAJM002-146_S146_L004"
 - "MEAJM002-147_S147_L004"
 - "MEAJM002-148_S148_L004"
 - "MEAJM002-149_S149_L004"
 - "MEAJM002-14_S14_L004"
 - "MEAJM002-150_S150_L004"
 - "MEAJM002-151_S151_L004"
 - "MEAJM002-152_S152_L004"
 - "MEAJM002-153_S153_L004"
 - "MEAJM002-154_S154_L004"
 - "MEAJM002-155_S155_L004"
 - "MEAJM002-156_S156_L004"
 - "MEAJM002-157_S157_L004"
 - "MEAJM002-158_S158_L004"
 - "MEAJM002-159_S159_L004"
 - "MEAJM002-15_S15_L004"
 - "MEAJM002-160_S160_L004"
 - "MEAJM002-161_S161_L004"
 - "MEAJM002-162_S162_L004"
 - "MEAJM002-163_S163_L004"
 - "MEAJM002-164_S164_L004"
 - "MEAJM002-165_S165_L004"
 - "MEAJM002-166_S166_L004"
 - "MEAJM002-167_S167_L004"
 - "MEAJM002-168_S168_L004"
 - "MEAJM002-169_S169_L004"
 - "MEAJM002-16_S16_L004"
 - "MEAJM002-170_S170_L004"
 - "MEAJM002-171_S171_L004"
 - "MEAJM002-172_S172_L004"
 - "MEAJM002-173_S173_L004"
 - "MEAJM002-174_S174_L004"
 - "MEAJM002-175_S175_L004"
 - "MEAJM002-176_S176_L004"
 - "MEAJM002-177_S177_L004"
 - "MEAJM002-178_S178_L004"
 - "MEAJM002-179_S179_L004"
 - "MEAJM002-17_S17_L004"
 - "MEAJM002-180_S180_L004"
 - "MEAJM002-181_S181_L004"
 - "MEAJM002-182_S182_L004"
 - "MEAJM002-183_S183_L004"
 - "MEAJM002-184_S184_L004"
 - "MEAJM002-185_S185_L004"
 - "MEAJM002-186_S186_L004"
 - "MEAJM002-187_S187_L004"
 - "MEAJM002-188_S188_L004"
 - "MEAJM002-189_S189_L004"
 - "MEAJM002-18_S18_L004"
 - "MEAJM002-190_S190_L004"
 - "MEAJM002-191_S191_L004"
 - "MEAJM002-192_S192_L004"
 - "MEAJM002-193_S193_L004"
 - "MEAJM002-194_S194_L004"
 - "MEAJM002-195_S195_L004"
 - "MEAJM002-196_S196_L004"
 - "MEAJM002-197_S197_L004"
 - "MEAJM002-198_S198_L004"
 - "MEAJM002-199_S199_L004"
 - "MEAJM002-19_S19_L004"
 - "MEAJM002-1_S1_L004"
 - "MEAJM002-200_S200_L004"
 - "MEAJM002-201_S201_L004"
 - "MEAJM002-202_S202_L004"
 - "MEAJM002-203_S203_L004"
 - "MEAJM002-204_S204_L004"
 - "MEAJM002-205_S205_L004"
 - "MEAJM002-206_S206_L004"
 - "MEAJM002-207_S207_L004"
 - "MEAJM002-208_S208_L004"
 - "MEAJM002-209_S209_L004"
 - "MEAJM002-20_S20_L004"
 - "MEAJM002-210_S210_L004"
 - "MEAJM002-211_S211_L004"
 - "MEAJM002-212_S212_L004"
 - "MEAJM002-213_S213_L004"
 - "MEAJM002-214_S214_L004"
 - "MEAJM002-215_S215_L004"
 - "MEAJM002-216_S216_L004"
 - "MEAJM002-217_S217_L004"
 - "MEAJM002-218_S218_L004"
 - "MEAJM002-219_S219_L004"
 - "MEAJM002-21_S21_L004"
 - "MEAJM002-220_S220_L004"
 - "MEAJM002-221_S221_L004"
 - "MEAJM002-222_S222_L004"
 - "MEAJM002-223_S223_L004"
 - "MEAJM002-224_S224_L004"
 - "MEAJM002-225_S225_L004"
 - "MEAJM002-226_S226_L004"
 - "MEAJM002-227_S227_L004"
 - "MEAJM002-228_S228_L004"
 - "MEAJM002-229_S229_L004"
 - "MEAJM002-22_S22_L004"
 - "MEAJM002-230_S230_L004"
 - "MEAJM002-231_S231_L004"
 - "MEAJM002-232_S232_L004"
 - "MEAJM002-233_S233_L004"
 - "MEAJM002-234_S234_L004"
 - "MEAJM002-235_S235_L004"
 - "MEAJM002-236_S236_L004"
 - "MEAJM002-237_S237_L004"
 - "MEAJM002-238_S238_L004"
 - "MEAJM002-239_S239_L004"
 - "MEAJM002-23_S23_L004"
 - "MEAJM002-240_S240_L004"
 - "MEAJM002-241_S241_L004"
 - "MEAJM002-242_S242_L004"
 - "MEAJM002-243_S243_L004"
 - "MEAJM002-244_S244_L004"
 - "MEAJM002-245_S245_L004"
 - "MEAJM002-246_S246_L004"
 - "MEAJM002-247_S247_L004"
 - "MEAJM002-248_S248_L004"
 - "MEAJM002-249_S249_L004"
 - "MEAJM002-24_S24_L004"
 - "MEAJM002-250_S250_L004"
 - "MEAJM002-251_S251_L004"
 - "MEAJM002-252_S252_L004"
 - "MEAJM002-253_S253_L004"
 - "MEAJM002-254_S254_L004"
 - "MEAJM002-255_S255_L004"
 - "MEAJM002-256_S256_L004"
 - "MEAJM002-257_S257_L004"
 - "MEAJM002-258_S258_L004"
 - "MEAJM002-259_S259_L004"
 - "MEAJM002-25_S25_L004"
 - "MEAJM002-260_S260_L004"
 - "MEAJM002-261_S261_L004"
 - "MEAJM002-262_S262_L004"
 - "MEAJM002-263_S263_L004"
 - "MEAJM002-264_S264_L004"
 - "MEAJM002-265_S265_L004"
 - "MEAJM002-266_S266_L004"
 - "MEAJM002-267_S267_L004"
 - "MEAJM002-268_S268_L004"
 - "MEAJM002-269_S269_L004"
 - "MEAJM002-26_S26_L004"
 - "MEAJM002-270_S270_L004"
 - "MEAJM002-271_S271_L004"
 - "MEAJM002-272_S272_L004"
 - "MEAJM002-273_S273_L004"
 - "MEAJM002-274_S274_L004"
 - "MEAJM002-275_S275_L004"
 - "MEAJM002-276_S276_L004"
 - "MEAJM002-277_S277_L004"
 - "MEAJM002-278_S278_L004"
 - "MEAJM002-279_S279_L004"
 - "MEAJM002-27_S27_L004"
 - "MEAJM002-280_S280_L004"
 - "MEAJM002-281_S281_L004"
 - "MEAJM002-282_S282_L004"
 - "MEAJM002-283_S283_L004"
 - "MEAJM002-284_S284_L004"
 - "MEAJM002-285_S285_L004"
 - "MEAJM002-286_S286_L004"
 - "MEAJM002-287_S287_L004"
 - "MEAJM002-288_S288_L004"
 - "MEAJM002-289_S289_L004"
 - "MEAJM002-28_S28_L004"
 - "MEAJM002-290_S290_L004"
 - "MEAJM002-291_S291_L004"
 - "MEAJM002-292_S292_L004"
 - "MEAJM002-293_S293_L004"
 - "MEAJM002-294_S294_L004"
 - "MEAJM002-295_S295_L004"
 - "MEAJM002-296_S296_L004"
 - "MEAJM002-297_S297_L004"
 - "MEAJM002-298_S298_L004"
 - "MEAJM002-299_S299_L004"
 - "MEAJM002-29_S29_L004"
 - "MEAJM002-2_S2_L004"
 - "MEAJM002-300_S300_L004"
 - "MEAJM002-301_S301_L004"
 - "MEAJM002-302_S302_L004"
 - "MEAJM002-303_S303_L004"
 - "MEAJM002-304_S304_L004"
 - "MEAJM002-305_S305_L004"
 - "MEAJM002-306_S306_L004"
 - "MEAJM002-307_S307_L004"
 - "MEAJM002-308_S308_L004"
 - "MEAJM002-309_S309_L004"
 - "MEAJM002-30_S30_L004"
 - "MEAJM002-310_S310_L004"
 - "MEAJM002-311_S311_L004"
 - "MEAJM002-312_S312_L004"
 - "MEAJM002-313_S313_L004"
 - "MEAJM002-314_S314_L004"
 - "MEAJM002-315_S315_L004"
 - "MEAJM002-316_S316_L004"
 - "MEAJM002-317_S317_L004"
 - "MEAJM002-318_S318_L004"
 - "MEAJM002-319_S319_L004"
 - "MEAJM002-31_S31_L004"
 - "MEAJM002-320_S320_L004"
 - "MEAJM002-321_S321_L004"
 - "MEAJM002-322_S322_L004"
 - "MEAJM002-323_S323_L004"
 - "MEAJM002-324_S324_L004"
 - "MEAJM002-325_S325_L004"
 - "MEAJM002-326_S326_L004"
 - "MEAJM002-327_S327_L004"
 - "MEAJM002-328_S328_L004"
 - "MEAJM002-329_S329_L004"
 - "MEAJM002-32_S32_L004"
 - "MEAJM002-330_S330_L004"
 - "MEAJM002-331_S331_L004"
 - "MEAJM002-332_S332_L004"
 - "MEAJM002-333_S333_L004"
 - "MEAJM002-334_S334_L004"
 - "MEAJM002-335_S335_L004"
 - "MEAJM002-336_S336_L004"
 - "MEAJM002-337_S337_L004"
 - "MEAJM002-338_S338_L004"
 - "MEAJM002-339_S339_L004"
 - "MEAJM002-33_S33_L004"
 - "MEAJM002-340_S340_L004"
 - "MEAJM002-341_S341_L004"
 - "MEAJM002-342_S342_L004"
 - "MEAJM002-343_S343_L004"
 - "MEAJM002-344_S344_L004"
 - "MEAJM002-345_S345_L004"
 - "MEAJM002-346_S346_L004"
 - "MEAJM002-347_S347_L004"
 - "MEAJM002-348_S348_L004"
 - "MEAJM002-349_S349_L004"
 - "MEAJM002-34_S34_L004"
 - "MEAJM002-350_S350_L004"
 - "MEAJM002-351_S351_L004"
 - "MEAJM002-352_S352_L004"
 - "MEAJM002-353_S353_L004"
 - "MEAJM002-354_S354_L004"
 - "MEAJM002-355_S355_L004"
 - "MEAJM002-356_S356_L004"
 - "MEAJM002-357_S357_L004"
 - "MEAJM002-358_S358_L004"
 - "MEAJM002-359_S359_L004"
 - "MEAJM002-35_S35_L004"
 - "MEAJM002-360_S360_L004"
 - "MEAJM002-361_S361_L004"
 - "MEAJM002-362_S362_L004"
 - "MEAJM002-363_S363_L004"
 - "MEAJM002-364_S364_L004"
 - "MEAJM002-365_S365_L004"
 - "MEAJM002-366_S366_L004"
 - "MEAJM002-367_S367_L004"
 - "MEAJM002-368_S368_L004"
 - "MEAJM002-369_S369_L004"
 - "MEAJM002-36_S36_L004"
 - "MEAJM002-370_S370_L004"
 - "MEAJM002-371_S371_L004"
 - "MEAJM002-372_S372_L004"
 - "MEAJM002-373_S373_L004"
 - "MEAJM002-374_S374_L004"
 - "MEAJM002-375_S375_L004"
 - "MEAJM002-376_S376_L004"
 - "MEAJM002-377_S377_L004"
 - "MEAJM002-378_S378_L004"
 - "MEAJM002-379_S379_L004"
 - "MEAJM002-37_S37_L004"
 - "MEAJM002-380_S380_L004"
 - "MEAJM002-381_S381_L004"
 - "MEAJM002-382_S382_L004"
 - "MEAJM002-383_S383_L004"
 - "MEAJM002-384_S384_L004"
 - "MEAJM002-385_S385_L004"
 - "MEAJM002-386_S386_L004"
 - "MEAJM002-387_S387_L004"
 - "MEAJM002-388_S388_L004"
 - "MEAJM002-389_S389_L004"
 - "MEAJM002-38_S38_L004"
 - "MEAJM002-390_S390_L004"
 - "MEAJM002-391_S391_L004"
 - "MEAJM002-392_S392_L004"
 - "MEAJM002-393_S393_L004"
 - "MEAJM002-394_S394_L004"
 - "MEAJM002-395_S395_L004"
 - "MEAJM002-396_S396_L004"
 - "MEAJM002-397_S397_L004"
 - "MEAJM002-398_S398_L004"
 - "MEAJM002-399_S399_L004"
 - "MEAJM002-39_S39_L004"
 - "MEAJM002-3_S3_L004"
 - "MEAJM002-400_S400_L004"
 - "MEAJM002-401_S401_L004"
 - "MEAJM002-402_S402_L004"
 - "MEAJM002-403_S403_L004"
 - "MEAJM002-404_S404_L004"
 - "MEAJM002-405_S405_L004"
 - "MEAJM002-406_S406_L004"
 - "MEAJM002-407_S407_L004"
 - "MEAJM002-408_S408_L004"
 - "MEAJM002-409_S409_L004"
 - "MEAJM002-40_S40_L004"
 - "MEAJM002-410_S410_L004"
 - "MEAJM002-411_S411_L004"
 - "MEAJM002-412_S412_L004"
 - "MEAJM002-413_S413_L004"
 - "MEAJM002-414_S414_L004"
 - "MEAJM002-415_S415_L004"
 - "MEAJM002-416_S416_L004"
 - "MEAJM002-417_S417_L004"
 - "MEAJM002-418_S418_L004"
 - "MEAJM002-419_S419_L004"
 - "MEAJM002-41_S41_L004"
 - "MEAJM002-420_S420_L004"
 - "MEAJM002-421_S421_L004"
 - "MEAJM002-422_S422_L004"
 - "MEAJM002-423_S423_L004"
 - "MEAJM002-424_S424_L004"
 - "MEAJM002-425_S425_L004"
 - "MEAJM002-426_S426_L004"
 - "MEAJM002-427_S427_L004"
 - "MEAJM002-428_S428_L004"
 - "MEAJM002-429_S429_L004"
 - "MEAJM002-42_S42_L004"
 - "MEAJM002-430_S430_L004"
 - "MEAJM002-431_S431_L004"
 - "MEAJM002-432_S432_L004"
 - "MEAJM002-433_S433_L004"
 - "MEAJM002-434_S434_L004"
 - "MEAJM002-435_S435_L004"
 - "MEAJM002-436_S436_L004"
 - "MEAJM002-437_S437_L004"
 - "MEAJM002-438_S438_L004"
 - "MEAJM002-439_S439_L004"
 - "MEAJM002-43_S43_L004"
 - "MEAJM002-440_S440_L004"
 - "MEAJM002-441_S441_L004"
 - "MEAJM002-442_S442_L004"
 - "MEAJM002-443_S443_L004"
 - "MEAJM002-444_S444_L004"
 - "MEAJM002-445_S445_L004"
 - "MEAJM002-446_S446_L004"
 - "MEAJM002-447_S447_L004"
 - "MEAJM002-448_S448_L004"
 - "MEAJM002-449_S449_L004"
 - "MEAJM002-44_S44_L004"
 - "MEAJM002-450_S450_L004"
 - "MEAJM002-451_S451_L004"
 - "MEAJM002-452_S452_L004"
 - "MEAJM002-453_S453_L004"
 - "MEAJM002-454_S454_L004"
 - "MEAJM002-455_S455_L004"
 - "MEAJM002-456_S456_L004"
 - "MEAJM002-457_S457_L004"
 - "MEAJM002-458_S458_L004"
 - "MEAJM002-459_S459_L004"
 - "MEAJM002-45_S45_L004"
 - "MEAJM002-460_S460_L004"
 - "MEAJM002-461_S461_L004"
 - "MEAJM002-462_S462_L004"
 - "MEAJM002-463_S463_L004"
 - "MEAJM002-464_S464_L004"
 - "MEAJM002-465_S465_L004"
 - "MEAJM002-466_S466_L004"
 - "MEAJM002-467_S467_L004"
 - "MEAJM002-468_S468_L004"
 - "MEAJM002-469_S469_L004"
 - "MEAJM002-46_S46_L004"
 - "MEAJM002-470_S470_L004"
 - "MEAJM002-471_S471_L004"
 - "MEAJM002-472_S472_L004"
 - "MEAJM002-473_S473_L004"
 - "MEAJM002-474_S474_L004"
 - "MEAJM002-475_S475_L004"
 - "MEAJM002-476_S476_L004"
 - "MEAJM002-477_S477_L004"
 - "MEAJM002-478_S478_L004"
 - "MEAJM002-479_S479_L004"
 - "MEAJM002-47_S47_L004"
 - "MEAJM002-480_S480_L004"
 - "MEAJM002-481_S481_L004"
 - "MEAJM002-482_S482_L004"
 - "MEAJM002-483_S483_L004"
 - "MEAJM002-48_S48_L004"
 - "MEAJM002-49_S49_L004"
 - "MEAJM002-4_S4_L004"
 - "MEAJM002-50_S50_L004"
 - "MEAJM002-51_S51_L004"
 - "MEAJM002-52_S52_L004"
 - "MEAJM002-53_S53_L004"
 - "MEAJM002-54_S54_L004"
 - "MEAJM002-55_S55_L004"
 - "MEAJM002-56_S56_L004"
 - "MEAJM002-57_S57_L004"
 - "MEAJM002-58_S58_L004"
 - "MEAJM002-59_S59_L004"
 - "MEAJM002-5_S5_L004"
 - "MEAJM002-60_S60_L004"
 - "MEAJM002-61_S61_L004"
 - "MEAJM002-62_S62_L004"
 - "MEAJM002-63_S63_L004"
 - "MEAJM002-64_S64_L004"
 - "MEAJM002-65_S65_L004"
 - "MEAJM002-66_S66_L004"
 - "MEAJM002-67_S67_L004"
 - "MEAJM002-68_S68_L004"
 - "MEAJM002-69_S69_L004"
 - "MEAJM002-6_S6_L004"
 - "MEAJM002-70_S70_L004"
 - "MEAJM002-71_S71_L004"
 - "MEAJM002-72_S72_L004"
 - "MEAJM002-73_S73_L004"
 - "MEAJM002-74_S74_L004"
 - "MEAJM002-75_S75_L004"
 - "MEAJM002-76_S76_L004"
 - "MEAJM002-77_S77_L004"
 - "MEAJM002-78_S78_L004"
 - "MEAJM002-79_S79_L004"
 - "MEAJM002-7_S7_L004"
 - "MEAJM002-80_S80_L004"
 - "MEAJM002-81_S81_L004"
 - "MEAJM002-82_S82_L004"
 - "MEAJM002-83_S83_L004"
 - "MEAJM002-84_S84_L004"
 - "MEAJM002-85_S85_L004"
 - "MEAJM002-86_S86_L004"
 - "MEAJM002-87_S87_L004"
 - "MEAJM002-88_S88_L004"
 - "MEAJM002-89_S89_L004"
 - "MEAJM002-8_S8_L004"
 - "MEAJM002-90_S90_L004"
 - "MEAJM002-91_S91_L004"
 - "MEAJM002-92_S92_L004"
 - "MEAJM002-93_S93_L004"
 - "MEAJM002-94_S94_L004"
 - "MEAJM002-95_S95_L004"
 - "MEAJM002-96_S96_L004"
 - "MEAJM002-97_S97_L004"
 - "MEAJM002-98_S98_L004"
 - "MEAJM002-99_S99_L004"
 - "MEAJM002-9_S9_L004"

# kmc parameters ============================================================================

## k-mer length
k: 31

## minimum k-mer count for kmc3
mincount: 5

## maximum k-mer count for kmc3
maxcount: 100000

## size of counting bloom filter array
array_size: 100000

## number of hash functions
num_hash: 4

## number of k-mer hits that a read needs to have to determine contamination
contam_match_limit_count: 1
contam_match_limit_percent: 1.0

# fastp parameters ==========================================================================

## unqualified_percent_limit for fastp: how many percents of bases are allowed to be unqualified in terms of quality score
unqualLimit: 40

## quality score for read trimming
qualThresh: 30

## window length for read trimming
windowLength: 1

## maximum number of N bases allowed per read
nBaseLimit: 5

# contaminants to include in read QC =========================================================

## contaminants to download from ncbi
#ncbi_contams:
        # - "human"
# - "viruses"
# - "eubacteria"
# - "fungi"
# - "archaea"

## custom contaminants, user provides fasta file
custom_contams:
 - "grenenet_pseudogenomes" 
   # - "grenenet-specific-kmers"
   #- "Athaliana_447_TAIR10"
